packages:
  - alvaro.cuesta.dev
  - xenon-ssg
  - xenon-ssg-express

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.3
  "@types/express": ^4.17.21
  temporal-polyfill: ^0.2.5
  xmlbuilder2: ^3.1.1
  "@types/react-dom": ^18.3.7
  type-fest: ^4.41.0
  vitest: ^3.2.4

allowBuilds:
  esbuild: true
  sharp: true
