import type { Program, CallExpression, Node } from "estree";
import { walk } from "estree-walker";

/**
 * Recma plugin that auto-injects `tableOfContents={tableOfContents}` into
 * `<TableOfContents />` JSX calls in compiled MDX, referencing the
 * `tableOfContents` export generated by `@stefanprobst/rehype-extract-toc/mdx`.
 *
 * Only injects the prop if the author hasn't explicitly provided it, so
 * `<TableOfContents tableOfContents={customToc} />` is left untouched.
 */
function transformer(ast: Program): void {
  walk(ast as unknown as Node, {
    enter(node) {
      if (node.type !== "CallExpression") return;

      const call = node as CallExpression;

      // Match _jsx(TableOfContents, { ... }), _jsxs(...), _jsxDEV(...)
      if (
        call.callee.type !== "Identifier" ||
        !["_jsx", "_jsxs", "_jsxDEV"].includes(call.callee.name)
      ) {
        return;
      }

      const firstArg = call.arguments[0];
      if (
        !firstArg ||
        firstArg.type !== "Identifier" ||
        firstArg.name !== "TableOfContents"
      ) {
        return;
      }

      const secondArg = call.arguments[1];
      if (!secondArg || secondArg.type !== "ObjectExpression") {
        return;
      }

      // Don't inject if the author already specified tableOfContents
      const alreadyHasProp = secondArg.properties.some(
        (prop) =>
          prop.type === "Property" &&
          prop.key.type === "Identifier" &&
          prop.key.name === "tableOfContents",
      );

      if (alreadyHasProp) return;

      // Add tableOfContents: tableOfContents (shorthand)
      secondArg.properties.push({
        type: "Property",
        key: { type: "Identifier", name: "tableOfContents" },
        value: { type: "Identifier", name: "tableOfContents" },
        kind: "init",
        method: false,
        shorthand: true,
        computed: false,
      });
    },
  });
}

const recmaInjectTocProp = () => transformer;

export default recmaInjectTocProp;
