name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [master]
    paths-ignore:
      - "**/README.md"
      - "**/TODO.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: alvaro.cuesta.dev

jobs:
  lint:
    name: Lint ${{ matrix.linter.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          - { name: "TypeScript", script: "lint:tsc" }
          # - { name: "Prettier", script: "lint:prettier" }
          # - { name: "ESLint", script: "lint:eslint" }
          # - { name: "Knip", script: "lint:knip" }
          # - { name: "Madge", script: "lint:madge" }
    steps:
      - &checkout
        name: Check out Git repository
        uses: actions/checkout@v4
        # We need the full history for "last modified" dates in blog posts
        with:
          fetch-depth: 0

      - &setup
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - &install_deps
        name: Install dependencies
        shell: bash
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Run ${{ matrix.linter.name }}
        run: npm run ${{ matrix.linter.script }}
        working-directory: ${{ env.BUILD_PATH }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup
      - *install_deps

      - name: Run tests
        run: npm test
        working-directory: ${{ env.BUILD_PATH }}

  build:
    name: Build
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - *checkout
      - *setup
      - *install_deps

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Xenon SSG
        env:
          XENON_ORIGIN: ${{ steps.pages.outputs.origin }}
          XENON_BASE_PATH: ${{ steps.pages.outputs.base_path }}
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
